### ISSUE TITLE
django-zero[dev] 

### ISSUE THREAD

**Issue by ojd2** [django-zero/django-zero#21]
Hello, any idea on as to why installing `django-zero[dev]` seems to be inaccessible right now? I seem to be receiving ` no matches found: django-zero[dev]` when using either `pip` & `pip3` 

node v = `v8.15.1` / `v10.15.3`

Has this command been updated recently? 

NOTE: After manually installing the dependencies: `honcho`, `medikit` & `cookiecutter` - I am able to install & create a project.

**Comment by hartym** [comment]
This is strange, are you able to provide a bit more details? It works for me as of now, I can't figure out why you would have this error. Do you have a specific setup, like using a non default pypi or something?
